project:
  type: website
  output-dir: docs

website:
  title: "Bishal Patel"
  navbar:
    right:
      - href: index.qmd
        text: HOME
      - href: about.qmd
        text: ABOUT
      - href: Project.qmd
        text: PROJECT
      # - href: blogs.qmd
      #   text: BLOGS
      # - href: gallery.qmd
      #   text: GALLERY
      - href: files/BP_Resume_2025.pdf
        text: RESUME

format:
  html:
    theme:
      dark: [darkly, styles-dark.scss]
      light: [litera, styles.scss] 
    highlight-style: a11y-dark
    mainfont: "Roboto"
    monofont: "Roboto Mono"
    code-copy: true
    code-overflow: wrap


execute:
  freeze: auto